# This file is a template, and might need editing before it works on your project.
# use the official gcc image, based on debian
# can use verions as well, like gcc:5.2
# see https://hub.docker.com/_/gcc/
image: "ruby:2.5"

build:
  stage: build
  # instead of calling g++ directly you can also use some build toolkit like make
  # install the necessary build tools when needed
  before_script:
    - apt-get update -y
    - apt-get install sudo -y
    - sudo apt-get install software-properties-common -y
    - sudo apt-get update -y
    - apt-get install ca-certificates
    #- sudo apt-add-repository ppa:brightbox/ruby-ng -y && sudo apt-get update -y
    #- sudo apt-get install ruby2.4 -y
    - gem install ceedling 
  script:
    - ceedling
  artifacts:
    #reports:
     # junit: build/artifacts/test/report.xml
    paths:
      - build/artifacts/test
      # depending on your build setup it's most likely a good idea to cache outputs to reduce the build time
      # cache:
      #   paths:
      #     - "*.o"


