# This file is a template, and might need editing before it works on your project.
# use the official gcc image, based on debian
# can use verions as well, like gcc:5.2
# see https://hub.docker.com/_/gcc/
image: gcc

build:
  stage: build
  # instead of calling g++ directly you can also use some build toolkit like make
  # install the necessary build tools when needed
  before_script:
    - sudo apt-add-repository ppa:brightbox/ruby-ng && sudo apt-get update -y
    - sudo apt-get install ruby2.4
    - gem install ceedling
  script:
    - ceedling
  artifacts:
    reports:
      junit: build/artifacts/test/git_ci_results.xml
    paths:
      - build/artifacts/test
      # depending on your build setup it's most likely a good idea to cache outputs to reduce the build time
      # cache:
      #   paths:
      #     - "*.o"


